# Test

In [1]:
from simulate import SIMPLE_SIMULATE_DAILY_TRADE_CHN_STK

# 数据格式

# 传入数据格式

endDate : 交易结束日期

initialHolding: DataFrame(data = shares+cash,index = date,columns = share_codes+cash_code)
initialholding为交易开始日期的股票和现金量，股票为股数，现金为金额

df_targetPortfolioWgt: DataFrame(data = shares+cash, index = rebalance dates, columns = share_codes+cash_code)
targetporfolio为股票和现金组合的比例

df_markToMarketPrice: DataFrame(data = shares+cash, index = trade dates)
marttomarketprice为投资组合每期的价格，数据为股票和现金的价格，现金的价格设为1

df_totalReturnFactor: DataFrame(data = shares+cash, index = trade dates)
totalreturnfactor为分红、拆股等的折算比例，数据为股票和现金的比例，现金每期设为1

df_excutePrice:       DataFrame(data = shares,      index = trade dates)
excuteprice为每期股票的价格，不包括现金

df_execPriceReturn:   DataFrame(data = shares,      index = trade dates)
execpricereturn为每期股票对应的回报率

df_tradeVolume:       DataFrame(data = shares,      index = trade dates)
df_tradevolume为每期市场股票交易数量，不摆阔现金

dict_tradingParam:(default)              
                            dict_tradingParam ={'canTradeOnSuspend':1,'RiseLimitThres':0.1,'FallLimitThres':-0.1,'VolumeLimitPct':0.1,'cash_code':'RMB','lotSize':100}
dict_tradingparam为初始设定的市场参数

# 传出数据格式

result = dict

# Sample

In [7]:
import pandas as pd
import tushare as ts
import numpy as np
api = ts.get_apis()
stock = ts.bar('600519',api,start_date = '2016-12-1',end_date = '2018-8-1',freq='1min')
stock = stock.sort_index(ascending = True)
stock_code = stock['code'][0]
cash_code = 'RMB'
dict_tradingParam = {'canTradeOnSuspend':1,'RiseLimitThres':1,'FallLimitThres':-1,'VolumeLimitPct':1,'cash_code':'RMB','lotSize':100}
beginDate = stock.index[0]
endDate = stock.index[-1]


df_targetPortfolioWgt = pd.DataFrame(np.ones((len(stock.index),2))*0.5,index = stock.index,columns =       [stock_code,cash_code])
initialHolding = pd.DataFrame(np.array([[20000,100]]),pd.date_range(beginDate,periods = 1),columns = [stock_code,cash_code])
df_markToMarketPrice = pd.DataFrame(stock['close'])
df_markToMarketPrice.columns = [stock_code]
df_markToMarketPrice[cash_code] = np.ones(len(stock['close']))

df_totalReturnFactor = pd.DataFrame(np.ones((len(stock['close']),2)),stock.index,columns = [stock_code,cash_code])
df_executePrice = pd.DataFrame(df_markToMarketPrice[stock_code])
df_execPriceReturn  = pd.DataFrame(np.random.randn(len(stock['close'])),stock.index,columns = [stock_code])
df_tradeVolume = pd.DataFrame(stock['vol'])
df_tradeVolume.columns = [stock_code]

SIMPLE_SIMULATE_DAILY_TRADE_CHN_STK(endDate, initialHolding, df_targetPortfolioWgt,
                                        df_markToMarketPrice, df_totalReturnFactor, df_executePrice,
                                        df_execPriceReturn, df_tradeVolume, dict_tradingParam)

{'CumulativeReturn':                        600519
 datetime
 2018-05-16 09:31:00 -0.000500
 2018-05-16 09:32:00  0.000306
 2018-05-16 09:33:00  0.002061
 2018-05-16 09:34:00  0.001925
 2018-05-16 09:35:00  0.001458
 2018-05-16 09:36:00  0.002867
 2018-05-16 09:37:00  0.004195
 2018-05-16 09:38:00  0.003504
 2018-05-16 09:39:00  0.002955
 2018-05-16 09:40:00  0.002169
 2018-05-16 09:41:00  0.003213
 2018-05-16 09:42:00  0.002874
 2018-05-16 09:43:00  0.003172
 2018-05-16 09:44:00  0.002630
 2018-05-16 09:45:00  0.002230
 2018-05-16 09:46:00  0.002183
 2018-05-16 09:47:00  0.002738
 2018-05-16 09:48:00  0.003145
 2018-05-16 09:49:00  0.002874
 2018-05-16 09:50:00  0.002176
 2018-05-16 09:51:00  0.001892
 2018-05-16 09:52:00  0.001519
 2018-05-16 09:53:00  0.001133
 2018-05-16 09:54:00  0.000780
 2018-05-16 09:55:00  0.000706
 2018-05-16 09:56:00  0.000835
 2018-05-16 09:57:00  0.000841
 2018-05-16 09:58:00  0.000835
 2018-05-16 09:59:00  0.001634
 2018-05-16 10:00:00  0.000225
 ...                       ...
 2018-08-01 14:31:00 -0.013632
 2018-08-01 14:32:00 -0.013427
 2018-08-01 14:33:00 -0.013639
 2018-08-01 14:34:00 -0.013434
 2018-08-01 14:35:00 -0.013885
 2018-08-01 14:36:00 -0.014556
 2018-08-01 14:37:00 -0.014303
 2018-08-01 14:38:00 -0.014303
 2018-08-01 14:39:00 -0.014453
 2018-08-01 14:40:00 -0.014118
 2018-08-01 14:41:00 -0.013564
 2018-08-01 14:42:00 -0.013584
 2018-08-01 14:43:00 -0.013420
 2018-08-01 14:44:00 -0.013085
 2018-08-01 14:45:00 -0.013427
 2018-08-01 14:46:00 -0.013495
 2018-08-01 14:47:00 -0.013434
 2018-08-01 14:48:00 -0.013358
 2018-08-01 14:49:00 -0.013701
 2018-08-01 14:50:00 -0.013769
 2018-08-01 14:51:00 -0.014002
 2018-08-01 14:52:00 -0.014180
 2018-08-01 14:53:00 -0.014180
 2018-08-01 14:54:00 -0.014221
 2018-08-01 14:55:00 -0.014255
 2018-08-01 14:56:00 -0.014248
 2018-08-01 14:57:00 -0.014193
 2018-08-01 14:58:00 -0.014193
 2018-08-01 14:59:00 -0.014070
 2018-08-01 15:00:00 -0.014152

 [13200 rows x 1 columns], 'Holding':                       600519         RMB
 datetime
 2018-05-16 09:31:00  10000.0  7372919.80
 2018-05-16 09:32:00  10000.0  7372919.80
 2018-05-16 09:33:00  10000.0  7372919.80
 2018-05-16 09:34:00  10000.0  7372919.80
 2018-05-16 09:35:00  10000.0  7372919.80
 2018-05-16 09:36:00  10000.0  7372919.80
 2018-05-16 09:37:00  10000.0  7372919.80
 2018-05-16 09:38:00  10000.0  7372919.80
 2018-05-16 09:39:00  10000.0  7372919.80
 2018-05-16 09:40:00  10000.0  7372919.80
 2018-05-16 09:41:00  10000.0  7372919.80
 2018-05-16 09:42:00  10000.0  7372919.80
 2018-05-16 09:43:00  10000.0  7372919.80
 2018-05-16 09:44:00  10000.0  7372919.80
 2018-05-16 09:45:00  10000.0  7372919.80
 2018-05-16 09:46:00  10000.0  7372919.80
 2018-05-16 09:47:00  10000.0  7372919.80
 2018-05-16 09:48:00  10000.0  7372919.80
 2018-05-16 09:49:00  10000.0  7372919.80
 2018-05-16 09:50:00  10000.0  7372919.80
 2018-05-16 09:51:00  10000.0  7372919.80
 2018-05-16 09:52:00  10000.0  7372919.80
 2018-05-16 09:53:00  10000.0  7372919.80
 2018-05-16 09:54:00  10000.0  7372919.80
 2018-05-16 09:55:00  10000.0  7372919.80
 2018-05-16 09:56:00  10000.0  7372919.80
 2018-05-16 09:57:00  10000.0  7372919.80
 2018-05-16 09:58:00  10000.0  7372919.80
 2018-05-16 09:59:00  10000.0  7372919.80
 2018-05-16 10:00:00  10000.0  7372919.80
 ...                      ...         ...
 2018-08-01 14:31:00  10100.0  7330713.34
 2018-08-01 14:32:00  10100.0  7330713.34
 2018-08-01 14:33:00  10100.0  7330713.34
 2018-08-01 14:34:00  10100.0  7330713.34
 2018-08-01 14:35:00  10100.0  7330713.34
 2018-08-01 14:36:00  10100.0  7330713.34
 2018-08-01 14:37:00  10100.0  7330713.34
 2018-08-01 14:38:00  10100.0  7330713.34
 2018-08-01 14:39:00  10100.0  7330713.34
 2018-08-01 14:40:00  10100.0  7330713.34
 2018-08-01 14:41:00  10100.0  7330713.34
 2018-08-01 14:42:00  10100.0  7330713.34
 2018-08-01 14:43:00  10100.0  7330713.34
 2018-08-01 14:44:00  10100.0  7330713.34
 2018-08-01 14:45:00  10100.0  7330713.34
 2018-08-01 14:46:00  10100.0  7330713.34
 2018-08-01 14:47:00  10100.0  7330713.34
 2018-08-01 14:48:00  10100.0  7330713.34
 2018-08-01 14:49:00  10100.0  7330713.34
 2018-08-01 14:50:00  10100.0  7330713.34
 2018-08-01 14:51:00  10100.0  7330713.34
 2018-08-01 14:52:00  10100.0  7330713.34
 2018-08-01 14:53:00  10100.0  7330713.34
 2018-08-01 14:54:00  10100.0  7330713.34
 2018-08-01 14:55:00  10100.0  7330713.34
 2018-08-01 14:56:00  10100.0  7330713.34
 2018-08-01 14:57:00  10100.0  7330713.34
 2018-08-01 14:58:00  10100.0  7330713.34
 2018-08-01 14:59:00  10100.0  7330713.34
 2018-08-01 15:00:00  10100.0  7330713.34

 [13200 rows x 2 columns], 'PortfolioValue':                           600519  RMB
 datetime
 2018-05-16 09:31:00  14753119.80  0.0
 2018-05-16 09:32:00  14765019.80  0.0
 2018-05-16 09:33:00  14790919.80  0.0
 2018-05-16 09:34:00  14788919.80  0.0
 2018-05-16 09:35:00  14782019.80  0.0
 2018-05-16 09:36:00  14802819.80  0.0
 2018-05-16 09:37:00  14822419.80  0.0
 2018-05-16 09:38:00  14812219.80  0.0
 2018-05-16 09:39:00  14804119.80  0.0
 2018-05-16 09:40:00  14792519.80  0.0
 2018-05-16 09:41:00  14807919.80  0.0
 2018-05-16 09:42:00  14802919.80  0.0
 2018-05-16 09:43:00  14807319.80  0.0
 2018-05-16 09:44:00  14799319.80  0.0
 2018-05-16 09:45:00  14793419.80  0.0
 2018-05-16 09:46:00  14792719.80  0.0
 2018-05-16 09:47:00  14800919.80  0.0
 2018-05-16 09:48:00  14806919.80  0.0
 2018-05-16 09:49:00  14802919.80  0.0
 2018-05-16 09:50:00  14792619.80  0.0
 2018-05-16 09:51:00  14788419.80  0.0
 2018-05-16 09:52:00  14782919.80  0.0
 2018-05-16 09:53:00  14777219.80  0.0
 2018-05-16 09:54:00  14772019.80  0.0
 2018-05-16 09:55:00  14770919.80  0.0
 2018-05-16 09:56:00  14772819.80  0.0
 2018-05-16 09:57:00  14772919.80  0.0
 2018-05-16 09:58:00  14772819.80  0.0
 2018-05-16 09:59:00  14784619.80  0.0
 2018-05-16 10:00:00  14763819.80  0.0
 ...                          ...  ...
 2018-08-01 14:31:00  14559283.34  0.0
 2018-08-01 14:32:00  14562313.34  0.0
 2018-08-01 14:33:00  14559182.34  0.0
 2018-08-01 14:34:00  14562212.34  0.0
 2018-08-01 14:35:00  14555546.34  0.0
 2018-08-01 14:36:00  14545648.34  0.0
 2018-08-01 14:37:00  14549385.34  0.0
 2018-08-01 14:38:00  14549385.34  0.0
 2018-08-01 14:39:00  14547163.34  0.0
 2018-08-01 14:40:00  14552112.34  0.0
 2018-08-01 14:41:00  14560293.34  0.0
 2018-08-01 14:42:00  14559990.34  0.0
 2018-08-01 14:43:00  14562414.34  0.0
 2018-08-01 14:44:00  14567363.34  0.0
 2018-08-01 14:45:00  14562313.34  0.0
 2018-08-01 14:46:00  14561303.34  0.0
 2018-08-01 14:47:00  14562212.34  0.0
 2018-08-01 14:48:00  14563323.34  0.0
 2018-08-01 14:49:00  14558273.34  0.0
 2018-08-01 14:50:00  14557263.34  0.0
 2018-08-01 14:51:00  14553829.34  0.0
 2018-08-01 14:52:00  14551203.34  0.0
 2018-08-01 14:53:00  14551203.34  0.0
 2018-08-01 14:54:00  14550597.34  0.0
 2018-08-01 14:55:00  14550092.34  0.0
 2018-08-01 14:56:00  14550193.34  0.0
 2018-08-01 14:57:00  14551001.34  0.0
 2018-08-01 14:58:00  14551001.34  0.0
 2018-08-01 14:59:00  14552819.34  0.0
 2018-08-01 15:00:00  14551607.34  0.0

 [13200 rows x 2 columns], 'SinglePeriodReturn':                        600519
 datetime
 2018-05-16 09:31:00 -0.000500
 2018-05-16 09:32:00  0.000807
 2018-05-16 09:33:00  0.001754
 2018-05-16 09:34:00 -0.000135
 2018-05-16 09:35:00 -0.000467
 2018-05-16 09:36:00  0.001407
 2018-05-16 09:37:00  0.001324
 2018-05-16 09:38:00 -0.000688
 2018-05-16 09:39:00 -0.000547
 2018-05-16 09:40:00 -0.000784
 2018-05-16 09:41:00  0.001041
 2018-05-16 09:42:00 -0.000338
 2018-05-16 09:43:00  0.000297
 2018-05-16 09:44:00 -0.000540
 2018-05-16 09:45:00 -0.000399
 2018-05-16 09:46:00 -0.000047
 2018-05-16 09:47:00  0.000554
 2018-05-16 09:48:00  0.000405
 2018-05-16 09:49:00 -0.000270
 2018-05-16 09:50:00 -0.000696
 2018-05-16 09:51:00 -0.000284
 2018-05-16 09:52:00 -0.000372
 2018-05-16 09:53:00 -0.000386
 2018-05-16 09:54:00 -0.000352
 2018-05-16 09:55:00 -0.000074
 2018-05-16 09:56:00  0.000129
 2018-05-16 09:57:00  0.000007
 2018-05-16 09:58:00 -0.000007
 2018-05-16 09:59:00  0.000799
 2018-05-16 10:00:00 -0.001407
 ...                       ...
 2018-08-01 14:31:00 -0.000049
 2018-08-01 14:32:00  0.000208
 2018-08-01 14:33:00 -0.000215
 2018-08-01 14:34:00  0.000208
 2018-08-01 14:35:00 -0.000458
 2018-08-01 14:36:00 -0.000680
 2018-08-01 14:37:00  0.000257
 2018-08-01 14:38:00  0.000000
 2018-08-01 14:39:00 -0.000153
 2018-08-01 14:40:00  0.000340
 2018-08-01 14:41:00  0.000562
 2018-08-01 14:42:00 -0.000021
 2018-08-01 14:43:00  0.000166
 2018-08-01 14:44:00  0.000340
 2018-08-01 14:45:00 -0.000347
 2018-08-01 14:46:00 -0.000069
 2018-08-01 14:47:00  0.000062
 2018-08-01 14:48:00  0.000076
 2018-08-01 14:49:00 -0.000347
 2018-08-01 14:50:00 -0.000069
 2018-08-01 14:51:00 -0.000236
 2018-08-01 14:52:00 -0.000180
 2018-08-01 14:53:00  0.000000
 2018-08-01 14:54:00 -0.000042
 2018-08-01 14:55:00 -0.000035
 2018-08-01 14:56:00  0.000007
 2018-08-01 14:57:00  0.000056
 2018-08-01 14:58:00  0.000000
 2018-08-01 14:59:00  0.000125
 2018-08-01 15:00:00 -0.000083

 [13200 rows x 1 columns], 'Turnover':                        600519
 datetime
 2018-05-16 09:31:00  0.499997
 2018-05-16 09:32:00  0.000000
 2018-05-16 09:33:00  0.000000
 2018-05-16 09:34:00  0.000000
 2018-05-16 09:35:00  0.000000
 2018-05-16 09:36:00  0.000000
 2018-05-16 09:37:00  0.000000
 2018-05-16 09:38:00  0.000000
 2018-05-16 09:39:00  0.000000
 2018-05-16 09:40:00  0.000000
 2018-05-16 09:41:00  0.000000
 2018-05-16 09:42:00  0.000000
 2018-05-16 09:43:00  0.000000
 2018-05-16 09:44:00  0.000000
 2018-05-16 09:45:00  0.000000
 2018-05-16 09:46:00  0.000000
 2018-05-16 09:47:00  0.000000
 2018-05-16 09:48:00  0.000000
 2018-05-16 09:49:00  0.000000
 2018-05-16 09:50:00  0.000000
 2018-05-16 09:51:00  0.000000
 2018-05-16 09:52:00  0.000000
 2018-05-16 09:53:00  0.000000
 2018-05-16 09:54:00  0.000000
 2018-05-16 09:55:00  0.000000
 2018-05-16 09:56:00  0.000000
 2018-05-16 09:57:00  0.000000
 2018-05-16 09:58:00  0.000000
 2018-05-16 09:59:00  0.000000
 2018-05-16 10:00:00  0.000000
 ...                       ...
 2018-08-01 14:31:00  0.000000
 2018-08-01 14:32:00  0.000000
 2018-08-01 14:33:00  0.000000
 2018-08-01 14:34:00  0.000000
 2018-08-01 14:35:00  0.000000
 2018-08-01 14:36:00  0.000000
 2018-08-01 14:37:00  0.000000
 2018-08-01 14:38:00  0.000000
 2018-08-01 14:39:00  0.000000
 2018-08-01 14:40:00  0.000000
 2018-08-01 14:41:00  0.000000
 2018-08-01 14:42:00  0.000000
 2018-08-01 14:43:00  0.000000
 2018-08-01 14:44:00  0.000000
 2018-08-01 14:45:00  0.000000
 2018-08-01 14:46:00  0.000000
 2018-08-01 14:47:00  0.000000
 2018-08-01 14:48:00  0.000000
 2018-08-01 14:49:00  0.000000
 2018-08-01 14:50:00  0.000000
 2018-08-01 14:51:00  0.000000
 2018-08-01 14:52:00  0.000000
 2018-08-01 14:53:00  0.000000
 2018-08-01 14:54:00  0.000000
 2018-08-01 14:55:00  0.000000
 2018-08-01 14:56:00  0.000000
 2018-08-01 14:57:00  0.000000
 2018-08-01 14:58:00  0.000000
 2018-08-01 14:59:00  0.000000
 2018-08-01 15:00:00  0.000000

 [13200 rows x 1 columns], 'Weights':                        600519       RMB
 datetime
 2018-05-16 09:31:00  0.500247  0.499753
 2018-05-16 09:32:00  0.500650  0.499350
 2018-05-16 09:33:00  0.501524  0.498476
 2018-05-16 09:34:00  0.501457  0.498543
 2018-05-16 09:35:00  0.501224  0.498776
 2018-05-16 09:36:00  0.501925  0.498075
 2018-05-16 09:37:00  0.502583  0.497417
 2018-05-16 09:38:00  0.502241  0.497759
 2018-05-16 09:39:00  0.501968  0.498032
 2018-05-16 09:40:00  0.501578  0.498422
 2018-05-16 09:41:00  0.502096  0.497904
 2018-05-16 09:42:00  0.501928  0.498072
 2018-05-16 09:43:00  0.502076  0.497924
 2018-05-16 09:44:00  0.501807  0.498193
 2018-05-16 09:45:00  0.501608  0.498392
 2018-05-16 09:46:00  0.501585  0.498415
 2018-05-16 09:47:00  0.501861  0.498139
 2018-05-16 09:48:00  0.502063  0.497937
 2018-05-16 09:49:00  0.501928  0.498072
 2018-05-16 09:50:00  0.501581  0.498419
 2018-05-16 09:51:00  0.501440  0.498560
 2018-05-16 09:52:00  0.501254  0.498746
 2018-05-16 09:53:00  0.501062  0.498938
 2018-05-16 09:54:00  0.500886  0.499114
 2018-05-16 09:55:00  0.500849  0.499151
 2018-05-16 09:56:00  0.500913  0.499087
 2018-05-16 09:57:00  0.500917  0.499083
 2018-05-16 09:58:00  0.500913  0.499087
 2018-05-16 09:59:00  0.501312  0.498688
 2018-05-16 10:00:00  0.500609  0.499391
 ...                       ...       ...
 2018-08-01 14:31:00  0.496492  0.503508
 2018-08-01 14:32:00  0.496597  0.503403
 2018-08-01 14:33:00  0.496489  0.503511
 2018-08-01 14:34:00  0.496593  0.503407
 2018-08-01 14:35:00  0.496363  0.503637
 2018-08-01 14:36:00  0.496020  0.503980
 2018-08-01 14:37:00  0.496150  0.503850
 2018-08-01 14:38:00  0.496150  0.503850
 2018-08-01 14:39:00  0.496073  0.503927
 2018-08-01 14:40:00  0.496244  0.503756
 2018-08-01 14:41:00  0.496527  0.503473
 2018-08-01 14:42:00  0.496517  0.503483
 2018-08-01 14:43:00  0.496600  0.503400
 2018-08-01 14:44:00  0.496771  0.503229
 2018-08-01 14:45:00  0.496597  0.503403
 2018-08-01 14:46:00  0.496562  0.503438
 2018-08-01 14:47:00  0.496593  0.503407
 2018-08-01 14:48:00  0.496632  0.503368
 2018-08-01 14:49:00  0.496457  0.503543
 2018-08-01 14:50:00  0.496422  0.503578
 2018-08-01 14:51:00  0.496303  0.503697
 2018-08-01 14:52:00  0.496213  0.503787
 2018-08-01 14:53:00  0.496213  0.503787
 2018-08-01 14:54:00  0.496192  0.503808
 2018-08-01 14:55:00  0.496174  0.503826
 2018-08-01 14:56:00  0.496178  0.503822
 2018-08-01 14:57:00  0.496206  0.503794
 2018-08-01 14:58:00  0.496206  0.503794
 2018-08-01 14:59:00  0.496269  0.503731
 2018-08-01 15:00:00  0.496227  0.503773

 [13200 rows x 2 columns]}

In [ ]:
import pandas as pd
import tushare as ts
import numpy as np
codes = ['000651','600519']
api = ts.get_apis()
stocks = []
for code in codes:
    stock = ts.bar(code,api,start_date = '2017-1-1',end_date = '2018-8-1').sort_index(ascending=True)
    stocks.append(stock)

In [ ]:
cash_code = 'RMB'
df_markToMarketPrice1 = pd.DataFrame(stocks[0]['close'])
df_markToMarketPrice1.columns = [stocks[0]['code'][0]]
df_markToMarketPrice2 = pd.DataFrame(stocks[1]['close'])
df_markToMarketPrice2.columns = [stocks[1]['code'][0]]
df_markToMarketPrice = pd.concat((df_markToMarketPrice1,df_markToMarketPrice2),axis=1)
df_markToMarketPrice[cash_code] = np.ones(len(df_markToMarketPrice.index))
beginDate = df_markToMarketPrice.index[0]
endDate = df_markToMarketPrice.index[-1]
all_codes = codes.copy()
all_codes.append(cash_code)
dict_tradingParam = {'canTradeOnSuspend':1,'RiseLimitThres':0.1,'FallLimitThres':-0.1,'VolumeLimitPct':0.1,'cash_code':'RMB','lotSize':100}

In [ ]:
initialHolding = pd.DataFrame(np.array([[200000,10000,100]]),pd.date_range(beginDate,periods = 1),columns = all_codes)

In [ ]:
df_targetPortfolioWgt = pd.DataFrame(np.ones((len(df_markToMarketPrice.index),3))/3,index = df_markToMarketPrice.index,columns = all_codes)

In [ ]:
df_totalReturnFactor = pd.DataFrame(np.ones((len(df_markToMarketPrice.index),3)),df_markToMarketPrice.index,columns = all_codes)

In [ ]:
df_executePrice = pd.DataFrame(df_markToMarketPrice[codes])

In [ ]:
df_tradeVolume = pd.concat((stocks[0]['vol'],stocks[1]['vol']),axis=1)
df_tradeVolume.columns = codes
df_execPriceReturn  = pd.DataFrame(np.random.randint(-100,100,size=(len(df_tradeVolume.index),2))/100,df_tradeVolume.index,columns = codes)

In [ ]:
SIMPLE_SIMULATE_DAILY_TRADE_CHN_STK(endDate, initialHolding, df_targetPortfolioWgt,
                                        df_markToMarketPrice, df_totalReturnFactor, df_executePrice,
                                        df_execPriceReturn, df_tradeVolume, dict_tradingParam)

In [12]:
def do_trade(w, price, commission,init_portfolio=None):
    """
    :param init_portfolio: t-1 时刻的 post trade 的 portfolio weight
    :param target_portfolio: t 时刻（及 t 以后时刻） portfolio weight，RL是每次给一期
    :param price: 后复权的价格
    :param commission: 交易费率，long 、short 的费率相同
    :return: t时刻开始的 NAV，仅在 portfolio 的 t 时刻有值
    """

    # t_portfolio = t_portfolio + t_minus_one_portfolio[-1] #把上一期叠到  target_portfolio 中
    # price = price.ix[t_portfolio.index]
    # ret = price / price.lag(1)
    # nav_pre = t_portfolio * price
    # cost =  sum( (t_portfolio - t_portfolio.lag(1) ) * price ) * commission
    # nav = nav - cost
    # return nav
    if init_portfolio:
        target_portfolio = target_portfolio + init_portfolio.ix[-1]
    price = price.ix[w.index]

    ret = price / price.shift(1)
    w__ = w.shift(1) * ret
    w__sum = w__.sum(axis=1)
    w_ = w__ / w__sum
    cost_ret = ((w - w_)).abs().sum(axis=1) * commission
    raw_ret = w__sum
    raw_ret.ix[0] = 1
    after_cost = raw_ret * (1 - cost_ret)
    after_cost_accu_ret = after_cost.prod()

    return after_cost_accu_ret



def batch_trade(target_port_wgt,price,commission,batch_size = 1000,init_portfolio_wgt=None):
    size = len(target_port_wgt.index)
    print(size)
    rets = []
    start = 0
    end = batch_size
    while start < size-1:
        if end <= (size-1):
            ret = do_trade(target_port_wgt[start:end],price,commission)
            rets.append(ret)
            start = end - 1
            end += batch_size
        else:
            ret = do_trade(target_port_wgt[start:size-1],price,commission)
            print(start)
            rets.append(ret)
            start = end-1
    result = np.array(rets).prod()-1

    return result

In [17]:
import time
start = time.clock()
print(batch_trade(df_targetPortfolioWgt,df_markToMarketPrice,0.001))
end = time.clock()
print(end-start)

13200

//anaconda/lib/python3.6/site-packages/pandas/core/generic.py:4441: RuntimeWarning: Cannot compare type 'Timestamp' with type 'str', sort order is undefined for incomparable objects
  other.columns, how=join, level=level, return_indexers=True)

12999
-0.013578282463942215
1.1704460000000267

In [14]:
import time
start = time.clock()
do_trade(df_targetPortfolioWgt,df_markToMarketPrice,0.001)
end = time.clock()
print(end-start)

//anaconda/lib/python3.6/site-packages/pandas/core/generic.py:4441: RuntimeWarning: Cannot compare type 'Timestamp' with type 'str', sort order is undefined for incomparable objects
  other.columns, how=join, level=level, return_indexers=True)

36.83537000000001

In [20]:
df_targetPortfolioWgt

                     600519  RMB
datetime
2018-05-16 09:31:00     0.5  0.5
2018-05-16 09:32:00     0.5  0.5
2018-05-16 09:33:00     0.5  0.5
2018-05-16 09:34:00     0.5  0.5
2018-05-16 09:35:00     0.5  0.5
2018-05-16 09:36:00     0.5  0.5
2018-05-16 09:37:00     0.5  0.5
2018-05-16 09:38:00     0.5  0.5
2018-05-16 09:39:00     0.5  0.5
2018-05-16 09:40:00     0.5  0.5
2018-05-16 09:41:00     0.5  0.5
2018-05-16 09:42:00     0.5  0.5
2018-05-16 09:43:00     0.5  0.5
2018-05-16 09:44:00     0.5  0.5
2018-05-16 09:45:00     0.5  0.5
2018-05-16 09:46:00     0.5  0.5
2018-05-16 09:47:00     0.5  0.5
2018-05-16 09:48:00     0.5  0.5
2018-05-16 09:49:00     0.5  0.5
2018-05-16 09:50:00     0.5  0.5
2018-05-16 09:51:00     0.5  0.5
2018-05-16 09:52:00     0.5  0.5
2018-05-16 09:53:00     0.5  0.5
2018-05-16 09:54:00     0.5  0.5
2018-05-16 09:55:00     0.5  0.5
2018-05-16 09:56:00     0.5  0.5
2018-05-16 09:57:00     0.5  0.5
2018-05-16 09:58:00     0.5  0.5
2018-05-16 09:59:00     0.5  0.5
2018-05-16 10:00:00     0.5  0.5
...                     ...  ...
2018-08-01 14:31:00     0.5  0.5
2018-08-01 14:32:00     0.5  0.5
2018-08-01 14:33:00     0.5  0.5
2018-08-01 14:34:00     0.5  0.5
2018-08-01 14:35:00     0.5  0.5
2018-08-01 14:36:00     0.5  0.5
2018-08-01 14:37:00     0.5  0.5
2018-08-01 14:38:00     0.5  0.5
2018-08-01 14:39:00     0.5  0.5
2018-08-01 14:40:00     0.5  0.5
2018-08-01 14:41:00     0.5  0.5
2018-08-01 14:42:00     0.5  0.5
2018-08-01 14:43:00     0.5  0.5
2018-08-01 14:44:00     0.5  0.5
2018-08-01 14:45:00     0.5  0.5
2018-08-01 14:46:00     0.5  0.5
2018-08-01 14:47:00     0.5  0.5
2018-08-01 14:48:00     0.5  0.5
2018-08-01 14:49:00     0.5  0.5
2018-08-01 14:50:00     0.5  0.5
2018-08-01 14:51:00     0.5  0.5
2018-08-01 14:52:00     0.5  0.5
2018-08-01 14:53:00     0.5  0.5
2018-08-01 14:54:00     0.5  0.5
2018-08-01 14:55:00     0.5  0.5
2018-08-01 14:56:00     0.5  0.5
2018-08-01 14:57:00     0.5  0.5
2018-08-01 14:58:00     0.5  0.5
2018-08-01 14:59:00     0.5  0.5
2018-08-01 15:00:00     0.5  0.5

[13200 rows x 2 columns]